### PR TITLE
DSD-2261: update default dataproc image for spark 3

### PR DESCRIPTION
**Pull request by creynolds15**

### CODE REVIEW

**Comment by tamr-github-integrator** [comment]
_No problems detected!_

**Review by ApekshaKhilari — APPROVED** [review]

**Review by souza-dan — COMMENTED** [review]
I might be wrong on this, but I believe the way the semantic release bot will pick up major versions is to have `BREAKING CHANGE` in the body of the commit.

So I think the message would need to look something like this:
```
feat:  update default dataproc image for spark 3

BREAKING CHANGE: default value for dataproc image has changed
```

**Comment by tamr-github-integrator** [comment]
_No problems detected!_

**Comment by creynolds15** [comment]
> I might be wrong on this, but I believe the way the semantic release bot will pick up major versions is to have `BREAKING CHANGE` in the body of the commit.
> 
> So I think the message would need to look something like this:
> 
> ```
> feat:  update default dataproc image for spark 3
> 
> BREAKING CHANGE: default value for dataproc image has changed
> ```

@souza-dan that is my fault on the commit message. I merged the PR here too fast: https://github.com/Datatamer/terraform-gcp-tamr-config. How can I resolve the version?

**Comment by souza-dan** [comment]
> 
Check the releases page. 
https://github.com/Datatamer/terraform-gcp-tamr-config/releases

You may be able to create a release manually.

**Comment by creynolds15** [comment]
> update default dataproc image for spark 3

Cool, that worked.

**Comment by tamr-github-integrator** [comment]
_No problems detected!_

**Pull request merged**
