### PR TITLE
DSD-2157: Update wrapper to use https.

### PR DESCRIPTION
**Pull request by creynolds15**

### CODE REVIEW

**Comment by tamr-github-integrator** [comment]
# [tfsec] Results
## Failed: 16 issue(s)
| # | ID | Severity | Title | Location | Description |
|---|----|----------|-------|----------|-------------|
| 1 | `google-compute-enable-shielded-vm-im` | *MEDIUM* | _Instances should have Shielded VM integrity monitoring enabled_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-vm.git?ref=v2.0.0/main.tf:43-98` | Instance does not have shielded VM integrity monitoring enabled. |
| 2 | `google-compute-enable-shielded-vm-vtpm` | *MEDIUM* | _Instances should have Shielded VM VTPM enabled_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-vm.git?ref=v2.0.0/main.tf:43-98` | Instance does not have VTPM for shielded VMs enabled. |
| 3 | `google-compute-no-project-wide-ssh-keys` | *MEDIUM* | _Disable project-wide SSH keys for all instances_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-vm.git?ref=v2.0.0/main.tf:43-98` | Instance allows use of project-level SSH keys. |
| 4 | `google-compute-vm-disk-encryption-customer-key` | *LOW* | _VM disks should be encrypted with Customer Supplied Encryption Keys_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-vm.git?ref=v2.0.0/main.tf:50-56` | Instance disk encryption does not use a customer managed key. |
| 5 | `google-iam-no-project-level-service-account-impersonation` | *MEDIUM* | _Users should not be granted service account access at the project level_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-iam?ref=v1.1.0/main.tf:65` | Service account access is granted to a user at project level. |
| 6 | `google-sql-enable-pg-temp-file-logging` | *MEDIUM* | _Temporary file logging should be enabled for all temporary files._ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-cloud-sql.git?ref=v5.0.0/main.tf:8-64` | Database instance has temporary file logging disabled. |
| 7 | `google-sql-encrypt-in-transit-data` | *HIGH* | _SSL connections to a SQL database instance should be enforced._ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-cloud-sql.git?ref=v5.0.0/main.tf:8-64` | Database instance does not require TLS for all connections. |
| 8 | `google-sql-no-public-access` | *HIGH* | _Ensure that Cloud SQL Database Instances are not publicly exposed_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-cloud-sql.git?ref=v5.0.0/main.tf:8-64` | Database instance is granted a public internet address. |
| 9 | `google-sql-pg-log-checkpoints` | *MEDIUM* | _Ensure that logging of checkpoints is enabled._ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-cloud-sql.git?ref=v5.0.0/main.tf:8-64` | Database instance is not configured to log checkpoints. |
| 10 | `google-sql-pg-log-connections` | *MEDIUM* | _Ensure that logging of connections is enabled._ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-cloud-sql.git?ref=v5.0.0/main.tf:8-64` | Database instance is not configured to log connections. |
| 11 | `google-sql-pg-log-disconnections` | *MEDIUM* | _Ensure that logging of disconnections is enabled._ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-cloud-sql.git?ref=v5.0.0/main.tf:8-64` | Database instance is not configured to log disconnections. |
| 12 | `google-sql-pg-log-lock-waits` | *MEDIUM* | _Ensure that logging of lock waits is enabled._ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-cloud-sql.git?ref=v5.0.0/main.tf:8-64` | Database instance is not configured to log lock waits. |
| 13 | `google-storage-bucket-encryption-customer-key` | *LOW* | _Cloud Storage buckets should be encrypted with a customer-managed key._ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-buckets.git?ref=v3.0.0/main.tf:42-54` | Storage bucket encryption does not use a customer-managed key. |
| 14 | `google-storage-bucket-encryption-customer-key` | *LOW* | _Cloud Storage buckets should be encrypted with a customer-managed key._ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-buckets.git?ref=v3.0.0/main.tf:13-25` | Storage bucket encryption does not use a customer-managed key. |
| 15 | `google-storage-enable-ubla` | *MEDIUM* | _Ensure that Cloud Storage buckets have uniform bucket-level access enabled_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-buckets.git?ref=v3.0.0/main.tf:42-54` | Bucket has uniform bucket level access disabled. |
| 16 | `google-storage-enable-ubla` | *MEDIUM* | _Ensure that Cloud Storage buckets have uniform bucket-level access enabled_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-buckets.git?ref=v3.0.0/main.tf:13-25` | Bucket has uniform bucket level access disabled. |

**Comment by tamr-github-integrator** [comment]
# [tfsec] Results
## Failed: 1 issue(s)
| # | ID | Severity | Title | Location | Description |
|---|----|----------|-------|----------|-------------|
| 1 | `google-compute-vm-disk-encryption-customer-key` | *LOW* | _VM disks should be encrypted with Customer Supplied Encryption Keys_ | `git::https:/github.com/Datatamer/terraform-gcp-tamr-vm.git?ref=v2.0.0/main.tf:50-56` | Instance disk encryption does not use a customer managed key. |

**Comment by tamr-github-integrator** [comment]
_No problems detected!_

**Review by souza-dan — COMMENTED** [review]
Content looks good.

Just a few things:
1. commit messages need to follow conventional commit structure in order 
https://www.conventionalcommits.org/en/v1.0.0/#summary
https://github.com/Datatamer/javasrc/blob/develop/.sharedhooks/README.md

So practically, I'd recommend rewriting your first commit as: 
`fix: uses https for source modules instead of ssh`

and your other commits you could probably squash into one:
`chore: adds tfsec ignore annotations`

2. The changelog and version need to be updated with the change:
https://github.com/Datatamer/terraform-gcp-tamr-wrapper/blob/https_link/CHANGELOG.md
https://github.com/Datatamer/terraform-gcp-tamr-wrapper/blob/https_link/VERSION

I'd consider this a bug fix, so it'll be a patch version increase (which is indicated by the `fix` commit).


If you're not very familiar with git rebasing, I'd be happy to walk through it or make these changes for you.

**Comment by tamr-github-integrator** [comment]
_No problems detected!_

**Comment by tamr-github-integrator** [comment]
_No problems detected!_

**Review by souza-dan — APPROVED** [review]
LGTM

**Pull request merged**
